name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v3
      - name: check linting and formatting.
        run: |
          npm ci
          cd test
          npm ci
          npm run lint:check
          npm run format:check
